baseURL: http://something-fresh.org/
languageCode: en-us
title: Rebuild schools and hospitals in Kharkiv
theme: hugo-fresh
googleAnalytics: # Put in your tracking code without quotes like this: UA-XXXXXX...
publishDir: docs
# Disables warnings
disableKinds:
- taxonomy
- taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true # Allows you to write raw html in your md files

params:
  # Open graph allows easy social sharing. If you don't want it you can set it to false or just delete the variable
  openGraph: true
  # Used as meta data; describe your site to make Google Bots happy
  description:
  navbarlogo:
  # Logo (from static/images/logos/___)
    image: logos/logo-long.jpg
    link: /
  font:
    name: "Open Sans"
    sizes: [400,600]
  hero:
    # Main hero title
    title: Rebuild schools and hospitals in Kharkiv
    # Hero subtitle (optional)
    subtitle: Nonprofit fund for schools and hospitals reconstruction in Kharkiv, Ukraine ðŸ‡ºðŸ‡¦
    # Button text
    buttontext: Donate
    # Where the main hero button links to
    buttonlink: "https://schoolsandhospitals.org/donate"
    # Hero image (from static/images/___)
    image: illustrations/worker.svg
    # Footer logos (from static/images/logos/clients/___.svg)
    clientlogos:
    - systek
    - tribe
    - kromo
    - infinite
    - gutwork
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: Our mission
    url: /mission
  - title: Getting involved
    sublinks:
    - title: Sign up for volunteering
      url: /volunteering
    - title: Donate
      url: /donate
    - title: ðŸ‡ºðŸ‡¦ Ð—Ð°Ð²Ð°Ð½Ñ‚Ð°Ð¶Ð¸Ñ‚Ð¸ Ð·Ñ€ÑƒÐ¹Ð½Ð¾Ð²Ð½Ñƒ ÑˆÐºÐ¾Ð»Ñƒ Ð°Ð±Ð¾ Ð»Ñ–ÐºÐ°Ñ€Ð½ÑŽ
      url: https://forms.gle/aBdVZbp6m91wdAYs8
  - title: Our contributors
    url: /contributors
  - title: Dameged schools and hospitals
    url: /evidences
  sidebar:
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
      - text: Profile
        url: /
      - text: Account
        url: /
      - text: Settings
        url: /
    - title: Messages
      icon: envelope
      links:
      - text: Inbox
        url: /
      - text: Compose
        url: /
    - title: Images
      icon: image
      links:
      - text: Library
        url: /
      - text: Upload
        url: /
    - title: Settings
      icon: cog
      links:
      - text: User settings
        url: /
      - text: App settings
        url: /
  section1:
    title: Great power comes
    subtitle: with great responsibility
    tiles:
    - title: App builder
      icon: mouse-globe
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Free trial
    - title: Cloud integration
      icon: laptop-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
    - title: Add-ons & plugins
      icon: plug-cloud
      text: This is some explanatory text that is on two rows
      url: /
      buttonText: Get started
  section2:
    title: You're here because you want the best
    subtitle: And we know it
    features:
    - title: Powerful and unified interface
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: Cross-device synchronisation
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: doc-sync
    - title: Nomad system
      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
      icon: mobile-feed
  section3:
    title: One platform
    subtitle: To rule them all
    image: illustrations/mockups/app-mockup.png
    buttonText: Get started
    buttonLink: "#"
  section4:
    title: Our Clients love us!
    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
    clients:
    - name: Irma Walters
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Accountant
      img: 1
    - name: John Bradley
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: Financial Analyst
      img: 2
    - name: Gary Blackman
      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
      job: HR Manager
      img: 3
  section5: true
  footer:
    # Logo (from /images/logos/___)
    logo: logo-alt.png
    # Social Media Title
    socialmediatitle: Contact Us
    # Social media links (GitHub, Twitter, etc.). All are optional.
    socialmedia:
    - link: https://instagram.com/schoolsandhospitals
      icon: instagram
    - link: mailto:rebuild@schoolsandhospitals.org
      icon: envelope
    bulmalogo: true
    quicklinks:
      column1:
        title: "Product"
        links:
        - text: Discover features
          link: /
        - text: Why choose our product?
          link: /
        - text: Compare features
          link: /
        - text: Our roadmap
          link: /
        - text: AGB
          link: /agb
      column2:
        title: "Docs"
        links:
        - text: Get started
          link: /
        - text: User guides
          link: /
        - text: Admin guide
          link: /
        - text: Developers
          link: /
      column3:
        title: "Blog"
        links:
        - text: Latest news
          link: /blog/first
        - text: Tech articles
          link: /blog/second
